version: "3"

services:
  apache-service:
    build: 
      context: apache-php
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - 8888:80
    volumes:
      - ${APP_PATH}:/var/www/html

  mysql-service:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
